"""initial migration

Revision ID: 59b1e6667ede
Revises:
Create Date: 2026-04-26 21:31:50.872129

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59b1e6667ede"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stations",
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column("public_phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trading_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_same_trading_and_brand_name", sa.Boolean(), nullable=False),
        sa.Column("brand_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("temporary_closure", sa.Boolean(), nullable=False),
        sa.Column("permanent_closure", sa.Boolean(), nullable=True),
        sa.Column("permanent_closure_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_motorway_service_station", sa.Boolean(), nullable=False),
        sa.Column("is_supermarket_service_station", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("station_id"),
    )
    op.create_table(
        "address",
        sa.Column("address_id", sa.Uuid(), nullable=False),
        sa.Column("address_line_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address_line_2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("county", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("postcode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.station_id"],
        ),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_table(
        "amenity",
        sa.Column("amenity_id", sa.Uuid(), nullable=False),
        sa.Column("amenity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.station_id"],
        ),
        sa.PrimaryKeyConstraint("amenity_id"),
    )
    op.create_table(
        "fuel_prices",
        sa.Column("fuel_price_id", sa.Uuid(), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum("B7_PREMIUM", "B7_STANDARD", "B10", "E5", "E10", "HVO", name="fueltype"),
            nullable=False,
        ),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("price_last_updated", sa.DateTime(), nullable=True),
        sa.Column("price_change_effective_timestamp", sa.DateTime(), nullable=True),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.station_id"],
        ),
        sa.PrimaryKeyConstraint("fuel_price_id"),
    )
    op.create_table(
        "fuel_types",
        sa.Column("fuel_type_id", sa.Uuid(), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum("B7_PREMIUM", "B7_STANDARD", "B10", "E5", "E10", "HVO", name="fueltype"),
            nullable=False,
        ),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.station_id"],
        ),
        sa.PrimaryKeyConstraint("fuel_type_id"),
    )
    op.create_table(
        "opening_times",
        sa.Column("opening_time_id", sa.Uuid(), nullable=False),
        sa.Column(
            "weekday",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                "BANK_HOLIDAY",
                name="weekday",
            ),
            nullable=False,
        ),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("open", sa.Time(), nullable=True),
        sa.Column("close", sa.Time(), nullable=True),
        sa.Column("is_24_hours", sa.Boolean(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.station_id"],
        ),
        sa.PrimaryKeyConstraint("opening_time_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opening_times")
    op.drop_table("fuel_types")
    op.drop_table("fuel_prices")
    op.drop_table("amenity")
    op.drop_table("address")
    op.drop_table("stations")
    # ### end Alembic commands ###
